[workspace]
resolver = "2"

members = [
    "lending-pool",
    "backstop-module",
    "emitter",
    "mocks/mock-blend-oracle",
    "pool-factory",
    "oracle"
]

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[patch.crates-io]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "38f3768" }
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "38f3768" }
soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "38f3768" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "38f3768" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "91cf595" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "91cf595" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "91cf595" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "91cf595" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "91cf595" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "5cca712b" }